# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b489fe60039ba7c3a19d50b95e5d21438053cfd07fe5f38d658b0b1f54a5b92988ddfe94d7acb413ae3d6478c35f80df8b4b9430b61ed3af13c3c17663a59b0

test:
  secret_key_base: 5f1f821463b9bc6b1617a6d030d5c83e51f9deb86e7547d1b55485da62d3c06910bcf84278dd008412f72fe63574cf2a65500774a8d295e8892381ac6774de59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
